Modem device icon: fix state detection (#4255)
Probably lacking an update from the NM-0.8 era, _update_state does
not correctly handle NM_DEVICE_STATE_IP_CHECK and
NM_DEVICE_STATE_SECONDARIES (triggered late in the connection-establishing
process after NM_DEVICE_STATE_IP_CONFIG).

This was causing backtraces like:
  File "/usr/share/sugar/extensions/deviceicon/network.py", line 856, in _update_state
    self._palette.update_state(gsm_state, reason)
  File "/usr/share/sugar/extensions/deviceicon/network.py", line 272, in update_state
    self._update_label_and_text(reason)
  File "/usr/share/sugar/extensions/deviceicon/network.py", line 310, in _update_label_and_text
    'text, %s' % str(self._current_state))
ValueError: Invalid GSM state while updating label and text, None

and it may have been confusing further code in the same class after.

Fix _update_state to more accurately identify the "connecting" states.

Signed-off-by: Ajay Garg <ajay@activitycentral.com>